---
title: "Lesson2 Plotting"
author: "Hirotaro Matsumoto"
date: "2022-10-04"
output: html_document
---

## Graphic system

### Base system

#### Example plot

```{r}
library(datasets)
data(cars)
with(cars, plot(speed, dist))
```

```{r}
library(datasets)
hist(airquality$Ozone)
```

```{r}
library(datasets)
with(airquality, plot(Wind, Ozone))
```

```{r}
library(datasets)
airquality <- transform(airquality, Month = factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")
```

```{r}
library(datasets)
with(airquality, plot(Wind, Ozone))
title(main = "Ozone and Wind in New York City")
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City", type = "n"))
with(subset(airquality, Month == 5), points(Wind, Ozone, col = "blue"))
with(subset(airquality, Month != 5), points(Wind, Ozone, col = "red"))
legend("topright", pch = 1, col = c("blue", "red"), legend = c("May", "Other Months"))
```

```{r}
with(airquality, plot(Wind, Ozone, main = "Ozone and Wind in New York City", pch = 20))
model <- lm(Ozone ~ Wind, airquality)
abline(model, lwd = 2)
```

```{r}
par(mfrow = c(1, 2))
with(airquality, {
    plot(Wind, Ozone, main = "Ozone and Wind")
    plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
})
```

```{r}
par(mfrow = c(1, 3), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
with(airquality, {
    plot(Wind, Ozone, main = "Ozone and Wind")
    plot(Solar.R, Ozone, main = "Ozone and Solar Radiation")
    plot(Temp, Ozone, main = "Ozone and Temperature")
    mtext("Ozone and Weather in New York City", outer = TRUE)
})
```

#### Parameter

-   pch

-   lty

-   lwd

-   col

-   xlab

-   ylab

#### par() function parameter

-   las

-   bg

-   mar

-   oma

-   mfrow

-   mfcol

#### plotting functions

-   plot

-   lines

-   points

-   text

-   title

-   mtext

-   axis

------------------------------------------------------------------------

### Lattice system

```{r}
library(lattice)
state <- data.frame(state.x77, region = state.region)
xyplot(Life.Exp ~ Income | region, data = state, layout = c(4, 1))
```

------------------------------------------------------------------------

### ggplot2 system

```{r}
library(ggplot2)
data(mpg)
qplot(displ, hwy, data = mpg)
```
